CREATE SEQUENCE WORKSHOP_SEQ START WITH 1000 INCREMENT BY 50;

CREATE TABLE WORKSHOP
(
    ID             INTEGER NOT NULL PRIMARY KEY,

    TITLE          VARCHAR NOT NULL,
    TOPIC          VARCHAR NOT NULL,
    INSTRUCTOR     VARCHAR NOT NULL,
    STATUS         VARCHAR NOT NULL,
    EXECUTION_DATE DATE    NOT NULL
);

ALTER TABLE WORKSHOP
    ADD CHECK (TOPIC IN ('SWOS', 'MOBIOT', 'METSS', 'BDAB', 'OSSA'));
ALTER TABLE WORKSHOP
    ADD CHECK (STATUS IN ('OPEN', 'FULL', 'CANCELED'));

CREATE SEQUENCE PARTICIPANT_SEQ START WITH 1000 INCREMENT BY 50;

CREATE TABLE PARTICIPANT
(
    ID          INTEGER NOT NULL PRIMARY KEY,

    FIRST_NAME  VARCHAR NOT NULL,
    LAST_NAME   VARCHAR NOT NULL,
    EMAIL       VARCHAR NOT NULL,

    WORKSHOP_ID INTEGER DEFAULT NULL
);

ALTER TABLE PARTICIPANT
    ADD CONSTRAINT FK_PARTICIPANT_WORKSHOP FOREIGN KEY (WORKSHOP_ID) REFERENCES WORKSHOP (ID);

